#!/usr/bin/with-contenv bash


# permissions (recursive) on Autorippr
chown -R abc:abc \
  /Autorippr-*

# permissions (non-recursive) on config root and folders
chown abc:abc \
	/config \
	/config/*
